name: Build PiFmAdv for Raspberry Pi 4 (arm64)

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: pi_fm_adv_build
      PROJECT_NAME: pi_fm_adv

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up QEMU for ARM64
      uses: docker/setup-qemu-action@main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@main

    - name: Build and run ARM64 container
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64/v8 -t pi_fm_adv_builder .
        docker run --rm -v $(pwd):/work -w /work pi_fm_adv_builder bash -c "git clone https://github.com/neu-aetd/PiFmAdv.git && cd PiFmAdv/src && make clean && make"

    - name: Copy compiled file and add date
      run: |
        mkdir -p $BUILD_DIR
        cp PiFmAdv/src/${PROJECT_NAME} $BUILD_DIR/${PROJECT_NAME}_$(date +%Y%m%d)
        echo "Build successful, binary saved to $BUILD_DIR with date suffix."

    - name: Archive artifacts
      uses: actions/upload-artifact@main
      with:
        name: pi_fm_adv_binaries
        path: ${{ env.BUILD_DIR }}
